const { MessageEmbed } = require("discord.js");
const data = require("../../data/data.json");
module.exports = {
  name: "eheavy",
  aliases: [],
  category: "information",
  description: "Este comando sirve para enviar la inavitacion del servidor",
  run: async (bot, message, args) => {
    const embed = new MessageEmbed()
      .setColor(data.color[1])
      .setTitle("ENFRENTAMIENTOS DIVISIÓN HEAVY")
      .setDescription(
        `
__**JORNADA 1**__
BAD BOYS vs GOD LEVEL
NIKA vs HISPANIC HUNTERS
LINZACOS vs HEAVEN'S QUEENS
MARCA PERÚ 3.3 vs NUEVO LAREDO
LA GUARDIA REAL vs STONE AGE!!
NOOBS vs BLACK DIAMOND
ACE OF SPADES vs NHANDEI ZHA
LIGA PARAGUAYA vs LEYENDA ROJA

__**JORNADA 2**__
BAD BOYS vs NIKA
GOD LEVEL vs LA MASACUATA
LINZACOS vs MARCA PERÚ 3.3
HEAVEN'S QUEENS vs TERROR HISPANO
LA GUARDIA REAL vs NOOBS
STONE AGE!! vs LOS PITUFOS
ACE OF SPADES vs LIGA PARAGUAYA
NHANDEI ZHA vs GUERREROS Z 3

__**JORNADA 3**__
BAD BOYS vs HISPANIC HUNTERS
NIKA vs LA MASACUATA
LINZACOS vs NUEVO LAREDO
MARCA PERÚ 3.3 vs TERROR HISPANO
LA GUARDIA REAL vs BLACK DIAMOND
NOOBS vs LOS PITUFOS
ACE OF SPADES vs LEYENDA ROJA
LIGA PARAGUAYA vs GUERREROS Z 3

__**JORNADA 4**__
BAD BOYS vs LA MASACUATA
GOD LEVEL vs HISPANIC HUNTERS
LINZACOS vs TERROR HISPANO
HEAVEN'S QUEENS vs NUEVO LAREDO
LA GUARDIA REAL vs LOS PITUFOS
STONE AGE!! vs BLACK DIAMOND
ACE OF SPADES vs GUERREROS Z 3
NHANDEI ZHA vs LEYENDA ROJA

__**JORNADA 5**__
GOD LEVEL vs NIKA
HISPANIC HUNTERS vs LA MASACUATA
HEAVEN'S QUEENS vs MARCA PERÚ 3.3
NUEVO LAREDO vs TERROR HISPANO
STONE AGE!! vs NOOBS
BLACK DIAMOND vs LOS PITUFOS
NHANDEI ZHA vs LIGA PARAGUAYA
LEYENDA ROJA vs GUERREROS Z 3`
      );
    message.channel.send(embed);
  },
};