const { MessageEmbed } = require("discord.js");
const data = require("../../data/data.json");
module.exports = {
  name: "elite",
  aliases: [],
  category: "information",
  description: "Este comando sirve para enviar la inavitacion del servidor",
  run: async (bot, message, args) => {
    const embed = new MessageEmbed()
      .setColor(data.color[1])
      .setTitle("ENFRENTAMIENTOS DIVISIÓN LITE")
      .setDescription(
        `
__**JORNADA 1**__
EL CAÑERO 2.0 vs ZOLOKOTROKO
LOS INTOCABLES vs SUICIDAL HEROS
KNIGHTS DARK vs ENVY US
TEAM LATINA vs LEGION TICA
VIRUS 502 vs BLOOD BROTHERS
GIRLS ONLY vs ORIGINAL Z
ALKILADOS vs EVIL WITCHES
EXILIADOS vs HALCONES WAUFF

__**JORNADA 2**__
EL CAÑERO vs LOS INTOCABLES
ZOLOKOTROKO vs COLDRAVER
KNIGHTS DARK vs TEAM LATINA
ENVY US vs ASSASSINS
VIRUS 502 vs GIRLS ONLY
BLOOD BROTHERS vs ARGENTINA 1986
ALKILADOS vs EXILIADOS
EVIL WITCHES vs WARASYLUM

__**JORNADA 3**__
EL CAÑERO vs SUICIDAL HEROS
LOS INTOCABLES vs COLDRAVER
KNIGHTS DARK vs LEGION TICA
TEAM LATINA vs ASSASSINS
VIRUS 502 vs ORIGINAL Z
GIRLS ONLY vs ARGENTINA 1986
ALKILADOS vs HALCONES WAUFF
EXILIADOS vs WARASYLUM

__**JORNADA 4**__
EL CAÑERO vs COLDRAVER
ZOLOKOTROKO vs SUICIDAL HEROS
KNIGHTS DARK vs ASSASSINS
ENVY US vs LEGION TICA
VIRUS 502 vs ARGENTINA 1986
BLOOD BROTHERS vs ORIGINAL Z
ALKILADOS vs WARASYLUM
EVIL WITCHES vs HALCONES WAUFF

__**JORNADA 5**__
ZOLOKOTROKO vs LOS INTOCABLES
SUICIDAL HEROS vs COLDRAVER
ENVY US vs TEAM LATINA
LEGION TICA vs ASSASSINS
BLOOD BROTHERS vs GIRLS ONLY
ORIGINAL Z vs ARGENTINA 1986
EVIL WITCHES vs EXILIADOS
HALCONES WAUFF vs WARASYLUM
					  `
      );
    message.channel.send(embed);
  },
};
